### ISSUE TITLE
Add flashbots_ rpc namespace support

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/mev-share-rs#27]
ref https://docs.flashbots.net/flashbots-auction/searchers/advanced/rpc-endpoint#flashbots_getuserstatsv2

## TODO
* add types + rpc trait, see existing eth/mev.rs

**Comment by optimiz-r** [comment]
I'm down to dive into this to get to know the repo better and gear up for #29.
If anybody's already on it, give me a shout. Otherwise, I'm on it from tomorrow.

**Comment by mattsse** [comment]
nice,

fyi the userstatsv2 type is already available
