### ISSUE TITLE
Support recursive bundle body 

### ISSUE THREAD

**Issue by mattsse** [paradigmxyz/mev-share-rs#8]
https://github.com/mattsse/mev-share-rs/blob/main/crates/mev-share-rpc-api/src/types.rs#L36-L36

currently lacks `bundle` variant of `SendBundleRequest`, needs to be boxed

however, the bundle composition is not really clear here:

> For example, to allow another searcher to backrun their bundle, one could include an empty object at the end of the body:

which kinda goes against the spec:

```
     body: Array<
            { hash: string } |
            { tx: string, canRevert: boolean } |
            { bundle: MevSendBundleParams }
        >,
```

so empty object wouldn't be allowed if this should actually be a `MevSendBundleParams`

matchmaker.tx has this https://github.com/flashbots/matchmaker-ts/blob/655af28247330c7dc3aea27158752201a7974d3f/src/api/interfaces.ts#L96 version is optional

**Comment by FrankieIsLost** [comment]
The team is removing the recursive bundle variant, so we only need to support hash and tx https://github.com/flashbots/mev-share/pull/15/files
